package de.muenchen.erzwingungshaft.xta.dto;

import genv3.de.xoev.schemata.basisdatentypen.x11.Code;
import genv3.eu.osci.ws.x2014.x10.transport.KeyCodeType;
import genv3.eu.osci.ws.x2014.x10.transport.QualifierType;
import jakarta.annotation.Nullable;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.With;

import java.math.BigInteger;
import java.time.ZonedDateTime;

/**
 * Represents the metadata of an XTA message.
 * @param service Distinct service in a certain business scenario context; in the XÖV context this is the "Dienste URI" (service URI). <p>This field is required.</p>
 * @param messageId Unique identifier of the message. <p>The ID is generated by the server and thus not required when sending.</p>
 * @param authorIdentifier Identifier of the author of the message. <p>This field is required.</p>
 * @param readerIdentifier Identifier of the reader of the message. <p>This field is required.</p>
 * @param messageSize Size of the message in bytes. <p>The size is determined by the server and thus not required when sending.</p>
 * @param deliveryAttributesOrigin Timestamp when the message was sent. <p>This field is only set for received messages and not required when sending.</p>
 * @param deliveryAttributesDelivery Timestamp when the message was delivered. <p>This field is only set for received messages and not required when sending.</p>
 */
public record XtaMessageMetaData(
        @NotBlank String service,
        @NotBlank XtaBusinessScenario businessScenario,
        @NotBlank XtaMessageType messageType,
        @With @Nullable String messageId,
        @NotNull @Valid XtaIdentifier authorIdentifier,
        @NotNull @Valid XtaIdentifier readerIdentifier,
        @Nullable @PositiveOrZero BigInteger messageSize,
        @Nullable ZonedDateTime deliveryAttributesOrigin,
        @Nullable ZonedDateTime deliveryAttributesDelivery
) {

}
