name: Build all

on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch: {}   # <<-- erlaubt manuelles Auslösen für Testläufe

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin # timezone
    strategy:
      fail-fast: false
      matrix:
        app-path: ["erzwingungshaft-eai"]
    outputs:
      # optional: expose artifact-name from the step that creates it, z.B. maven or node step
      artifact-name: ${{ steps.maven.outputs.artifact-name || steps.node.outputs.artifact-name || '' }}

    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@e012d3bda6f9d5511415e2d885f32826049284a4 # v1.0.23
      - if: ${{ hashFiles(format('./{0}/package.json', matrix.app-path))!=null }}
        id: node
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@e012d3bda6f9d5511415e2d885f32826049284a4 # v1.0.23
        with:
          app-path: ${{ matrix.app-path }}
      - if: ${{ hashFiles(format('./{0}/pom.xml', matrix.app-path))!=null }}
        id: maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@e012d3bda6f9d5511415e2d885f32826049284a4 # v1.0.23
        with:
          app-path: ${{ matrix.app-path }}
      - if: github.ref == 'refs/heads/main'
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@e012d3bda6f9d5511415e2d885f32826049284a4 # v1.0.23
        with:
          path: ${{ matrix.app-path }}
          image-name: ${{ matrix.app-path }}
          artifact-name: ${{ join(steps.*.outputs.artifact-name) }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
          image-tags: |
            type=raw,value=dev

  build_external_image:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' }} # läuft nur bei manueller Ausführung
    steps:
      - name: Checkout target branch (it-at-m/xjustiz@bugfix-missing-xsi-schema-location)
        uses: actions/checkout@v3
        with:
          repository: it-at-m/xjustiz
          ref: bugfix-missing-xsi-schema-location
          path: xjustiz-external

      - name: Build image from external repo
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@e012d3bda6f9d5511415e2d885f32826049284a4
        with:
          path: xjustiz-external
          image-name: it-at-m/xjustiz-bugfix-missing-xsi
          # optional: use artifact produced by the main build job (wenn benötigt)
          artifact-name: ${{ needs.build.outputs.artifact-name }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
          image-tags: |
            type=raw,value=dev
